version: "3.9"
services:
  renameme:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/renameme
      - SPRING_DATASOURCE_USER=postgres
      - SPRIG_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - ../db/renameme-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres